### ISSUE TITLE
Problem with v1.9

### ISSUE THREAD

**Issue by JLD95** [maartentamboer/X-Touch-Mini-FS2020#104]
Hi,
at start, I have this error

C:\Utilitaires\MFS\X-Touch-Mini-FS2020>X-Touch-Mini-FS2020.exe
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "configfile.py", line 3, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "eventqueue.py", line 3, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "conditionalrunner.py", line 1, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\jinja2\__init__.py", line 12, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\jinja2\environment.py", line 25, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\jinja2\defaults.py", line 3, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  **File "site-packages\jinja2\filters.py", line 13, in <module>
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Utilitaires\MFS\X-Touch-Mini-FS2020\markupsafe\__init__.pyc)
[33432] Failed to execute script main**

I don't have this file <markupsafe_init_.pyc>, only a subfolder <markupsafe> which contains <_speedups.cp37-win_amd64.pyd>

Previous  v1.8.1 works fine.

**Comment by Koseng** [comment]
Can confirm. Doesn't work on my system as well. @maartentamboer different jinja2 version used?

**Comment by maartentamboer** [comment]
Apparently one of the packages that jinja depends on had a breaking change. I will see if I can make a fix by directly including the old version
https://github.com/pallets/markupsafe/issues/286

**Comment by maartentamboer** [comment]
Fix is released: https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.9.1
