### ISSUE TITLE
Help with installation please

### ISSUE THREAD

**Issue by P1NBA11ER** [maartentamboer/X-Touch-Mini-FS2020#9]
Sorry for bothering you with troubleshooting... unfortunately, I'm finding the instructions lack enough detail for me to make this work. I've downloaded and run the exe after launching the sim (from various screens through to sitting at the gate) as well as before launching the sim. I have the Behringer utility installed and it recognizes my device. SimConnect is installed (it's part of the FS2020 SDK which I have installed). It doesn't seem to be working however and I have no idea how to proceed. Thanks for any help.

**Comment by maartentamboer** [comment]
Do you see any errors in the console window that opens? 
In case the console window directly closes: open a command prompt and navigate to the directory where the exe is located. Then run the exe in the command prompt

**Comment by P1NBA11ER** [comment]
Thanks for replying. I was not seeing an error in the command when executing the exe normally but I do see the error running it from the command prompt. Here's the text from the error.

Current aircraft: b'Airbus A320 Neo AirCal'
Traceback (most recent call last):
  File "main.py", line 100, in <module>
  File "main.py", line 31, in main_app
  File "site-packages\mido\backends\backend.py", line 112, in open_output
  File "site-packages\mido\ports.py", line 265, in __init__
  File "site-packages\mido\ports.py", line 86, in __init__
  File "site-packages\mido\backends\rtmidi.py", line 190, in _open
  File "site-packages\mido\backends\rtmidi.py", line 96, in _open_port
  File "src\_rtmidi.pyx", line 589, in rtmidi._rtmidi.MidiBase.open_port
  File "src\_rtmidi.pyx", line 223, in rtmidi._rtmidi._cb_error_func
  File "src\_rtmidi.pyx", line 411, in rtmidi._rtmidi._default_error_handler
rtmidi._rtmidi.SystemError: MidiOutWinMM::openPort: error creating Windows MM MIDI output port.
[13904] Failed to execute script main

**Comment by P1NBA11ER** [comment]
I've solved this problem by deleting hidden duplicate devices via the device manager. It seems windows may leave a port occupied by a device that's no longer in use by the system and perhaps I had reached the port limit? Thanks so much for your response, that was the direction I needed to get on a path of solving this.

**Comment by maartentamboer** [comment]
No problem. If you have any other questions, issues or feature requests feel free to open another issue.
